services:
  app:
    build: .
    container_name: blocklist-service
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SOT_URL=https://raw.githubusercontent.com/stamparm/ipsum/master/levels/1.txt
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SYNCHRONIZER_SECONDS_REFRESH=300 # 300 to try to synchronize every 5 minutes

  redis:
    restart: always
    image: redis:alpine
    container_name: redis-blocklist
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  redis-data:
    driver: local